/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SovAdsManager } from "./SovAdsManager";
export type { SovAdsStreaming } from "./SovAdsStreaming";
export type { SovAdsToken } from "./SovAdsToken";
