/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface SovadGsInterface extends utils.Interface {
  functions: {
    "addAdmin(address)": FunctionFragment;
    "adminList(uint256)": FunctionFragment;
    "adminTopup(uint256)": FunctionFragment;
    "adminWithdraw(address,uint256)": FunctionFragment;
    "admins(address)": FunctionFragment;
    "batchBlacklist(address[])": FunctionFragment;
    "batchSend(address[],uint256[])": FunctionFragment;
    "batchWhitelist(address[])": FunctionFragment;
    "blacklist(address)": FunctionFragment;
    "blacklistAddress(address)": FunctionFragment;
    "blacklistedAddresses(uint256)": FunctionFragment;
    "campaigns(bytes32)": FunctionFragment;
    "cancelClaim(bytes32)": FunctionFragment;
    "claimDateClaim(bytes32[])": FunctionFragment;
    "claimDirect(address,uint256,bytes32)": FunctionFragment;
    "claims(bytes32)": FunctionFragment;
    "endCampaign(bytes32)": FunctionFragment;
    "fundCampaign(bytes32,uint256)": FunctionFragment;
    "getCampaignDetails(bytes32)": FunctionFragment;
    "getClaim(bytes32)": FunctionFragment;
    "getTreasuryBalance()": FunctionFragment;
    "gsToken()": FunctionFragment;
    "initiateClaim(address,uint256,bytes32,bytes32)": FunctionFragment;
    "isParticipant(bytes32,address)": FunctionFragment;
    "joinCampaign(bytes32)": FunctionFragment;
    "manager()": FunctionFragment;
    "owner()": FunctionFragment;
    "participants(bytes32,address)": FunctionFragment;
    "removeAdmin(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setManager(address)": FunctionFragment;
    "setWhitelistEnabled(bool)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unblacklistAddress(address)": FunctionFragment;
    "unwhitelistAddress(address)": FunctionFragment;
    "whitelist(address)": FunctionFragment;
    "whitelistAddress(address)": FunctionFragment;
    "whitelistEnabled()": FunctionFragment;
    "whitelistedAddresses(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addAdmin"
      | "adminList"
      | "adminTopup"
      | "adminWithdraw"
      | "admins"
      | "batchBlacklist"
      | "batchSend"
      | "batchWhitelist"
      | "blacklist"
      | "blacklistAddress"
      | "blacklistedAddresses"
      | "campaigns"
      | "cancelClaim"
      | "claimDateClaim"
      | "claimDirect"
      | "claims"
      | "endCampaign"
      | "fundCampaign"
      | "getCampaignDetails"
      | "getClaim"
      | "getTreasuryBalance"
      | "gsToken"
      | "initiateClaim"
      | "isParticipant"
      | "joinCampaign"
      | "manager"
      | "owner"
      | "participants"
      | "removeAdmin"
      | "renounceOwnership"
      | "setManager"
      | "setWhitelistEnabled"
      | "transferOwnership"
      | "unblacklistAddress"
      | "unwhitelistAddress"
      | "whitelist"
      | "whitelistAddress"
      | "whitelistEnabled"
      | "whitelistedAddresses"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "adminList",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "adminTopup",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "adminWithdraw",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "admins",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "batchBlacklist",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSend",
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchWhitelist",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklist",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistedAddresses",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelClaim",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDateClaim",
    values: [PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDirect",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "claims",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "endCampaign",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "fundCampaign",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignDetails",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaim",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTreasuryBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gsToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initiateClaim",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isParticipant",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "joinCampaign",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "manager", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "participants",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setManager",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setWhitelistEnabled",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "unblacklistAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "unwhitelistAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelist",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistedAddresses",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "adminList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "adminTopup", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "adminWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "batchSend", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "blacklist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blacklistAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimDateClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimDirect",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claims", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "endCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTreasuryBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gsToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initiateClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "joinCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "manager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "participants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setManager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setWhitelistEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unblacklistAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unwhitelistAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "whitelist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "whitelistAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistedAddresses",
    data: BytesLike
  ): Result;

  events: {
    "AddressBlacklisted(address,uint256)": EventFragment;
    "AddressUnblacklisted(address,uint256)": EventFragment;
    "AddressUnwhitelisted(address,uint256)": EventFragment;
    "AddressWhitelisted(address,uint256)": EventFragment;
    "AdminAdded(address,uint256)": EventFragment;
    "AdminRemoved(address,uint256)": EventFragment;
    "AdminTopup(address,uint256,uint256)": EventFragment;
    "AdminWithdraw(address,address,uint256,uint256)": EventFragment;
    "BatchSend(address,uint256,uint256,uint256)": EventFragment;
    "CampaignEnded(bytes32,uint256)": EventFragment;
    "CampaignFunded(bytes32,uint256,uint256)": EventFragment;
    "CampaignJoined(bytes32,address,uint256)": EventFragment;
    "ClaimCancelled(bytes32,uint256)": EventFragment;
    "ClaimDirect(address,uint256,uint256)": EventFragment;
    "ClaimDistributed(bytes32,address,uint256,uint256)": EventFragment;
    "ClaimInitiated(bytes32,address,uint256,uint256)": EventFragment;
    "ManagerUpdated(address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "WhitelistToggled(bool,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddressBlacklisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AddressUnblacklisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AddressUnwhitelisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AddressWhitelisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AdminAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AdminRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AdminTopup"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AdminWithdraw"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BatchSend"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CampaignEnded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CampaignFunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CampaignJoined"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimDirect"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimDistributed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimInitiated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ManagerUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WhitelistToggled"): EventFragment;
}

export interface AddressBlacklistedEventObject {
  account: string;
  timestamp: BigNumber;
}
export type AddressBlacklistedEvent = TypedEvent<
  [string, BigNumber],
  AddressBlacklistedEventObject
>;

export type AddressBlacklistedEventFilter =
  TypedEventFilter<AddressBlacklistedEvent>;

export interface AddressUnblacklistedEventObject {
  account: string;
  timestamp: BigNumber;
}
export type AddressUnblacklistedEvent = TypedEvent<
  [string, BigNumber],
  AddressUnblacklistedEventObject
>;

export type AddressUnblacklistedEventFilter =
  TypedEventFilter<AddressUnblacklistedEvent>;

export interface AddressUnwhitelistedEventObject {
  account: string;
  timestamp: BigNumber;
}
export type AddressUnwhitelistedEvent = TypedEvent<
  [string, BigNumber],
  AddressUnwhitelistedEventObject
>;

export type AddressUnwhitelistedEventFilter =
  TypedEventFilter<AddressUnwhitelistedEvent>;

export interface AddressWhitelistedEventObject {
  account: string;
  timestamp: BigNumber;
}
export type AddressWhitelistedEvent = TypedEvent<
  [string, BigNumber],
  AddressWhitelistedEventObject
>;

export type AddressWhitelistedEventFilter =
  TypedEventFilter<AddressWhitelistedEvent>;

export interface AdminAddedEventObject {
  admin: string;
  timestamp: BigNumber;
}
export type AdminAddedEvent = TypedEvent<
  [string, BigNumber],
  AdminAddedEventObject
>;

export type AdminAddedEventFilter = TypedEventFilter<AdminAddedEvent>;

export interface AdminRemovedEventObject {
  admin: string;
  timestamp: BigNumber;
}
export type AdminRemovedEvent = TypedEvent<
  [string, BigNumber],
  AdminRemovedEventObject
>;

export type AdminRemovedEventFilter = TypedEventFilter<AdminRemovedEvent>;

export interface AdminTopupEventObject {
  token: string;
  amount: BigNumber;
  timestamp: BigNumber;
}
export type AdminTopupEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  AdminTopupEventObject
>;

export type AdminTopupEventFilter = TypedEventFilter<AdminTopupEvent>;

export interface AdminWithdrawEventObject {
  token: string;
  to: string;
  amount: BigNumber;
  timestamp: BigNumber;
}
export type AdminWithdrawEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  AdminWithdrawEventObject
>;

export type AdminWithdrawEventFilter = TypedEventFilter<AdminWithdrawEvent>;

export interface BatchSendEventObject {
  token: string;
  totalAmount: BigNumber;
  recipientCount: BigNumber;
  timestamp: BigNumber;
}
export type BatchSendEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  BatchSendEventObject
>;

export type BatchSendEventFilter = TypedEventFilter<BatchSendEvent>;

export interface CampaignEndedEventObject {
  campaignId: string;
  timestamp: BigNumber;
}
export type CampaignEndedEvent = TypedEvent<
  [string, BigNumber],
  CampaignEndedEventObject
>;

export type CampaignEndedEventFilter = TypedEventFilter<CampaignEndedEvent>;

export interface CampaignFundedEventObject {
  campaignId: string;
  amount: BigNumber;
  timestamp: BigNumber;
}
export type CampaignFundedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  CampaignFundedEventObject
>;

export type CampaignFundedEventFilter = TypedEventFilter<CampaignFundedEvent>;

export interface CampaignJoinedEventObject {
  campaignId: string;
  participant: string;
  timestamp: BigNumber;
}
export type CampaignJoinedEvent = TypedEvent<
  [string, string, BigNumber],
  CampaignJoinedEventObject
>;

export type CampaignJoinedEventFilter = TypedEventFilter<CampaignJoinedEvent>;

export interface ClaimCancelledEventObject {
  ref: string;
  timestamp: BigNumber;
}
export type ClaimCancelledEvent = TypedEvent<
  [string, BigNumber],
  ClaimCancelledEventObject
>;

export type ClaimCancelledEventFilter = TypedEventFilter<ClaimCancelledEvent>;

export interface ClaimDirectEventObject {
  recipient: string;
  amount: BigNumber;
  timestamp: BigNumber;
}
export type ClaimDirectEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  ClaimDirectEventObject
>;

export type ClaimDirectEventFilter = TypedEventFilter<ClaimDirectEvent>;

export interface ClaimDistributedEventObject {
  ref: string;
  recipient: string;
  amount: BigNumber;
  timestamp: BigNumber;
}
export type ClaimDistributedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  ClaimDistributedEventObject
>;

export type ClaimDistributedEventFilter =
  TypedEventFilter<ClaimDistributedEvent>;

export interface ClaimInitiatedEventObject {
  ref: string;
  recipient: string;
  amount: BigNumber;
  timestamp: BigNumber;
}
export type ClaimInitiatedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  ClaimInitiatedEventObject
>;

export type ClaimInitiatedEventFilter = TypedEventFilter<ClaimInitiatedEvent>;

export interface ManagerUpdatedEventObject {
  manager: string;
  timestamp: BigNumber;
}
export type ManagerUpdatedEvent = TypedEvent<
  [string, BigNumber],
  ManagerUpdatedEventObject
>;

export type ManagerUpdatedEventFilter = TypedEventFilter<ManagerUpdatedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface WhitelistToggledEventObject {
  enabled: boolean;
  timestamp: BigNumber;
}
export type WhitelistToggledEvent = TypedEvent<
  [boolean, BigNumber],
  WhitelistToggledEventObject
>;

export type WhitelistToggledEventFilter =
  TypedEventFilter<WhitelistToggledEvent>;

export interface SovadGs extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SovadGsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    adminList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    adminTopup(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    adminWithdraw(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    admins(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    batchBlacklist(
      accounts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    batchSend(
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    batchWhitelist(
      accounts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    blacklist(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    blacklistAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    blacklistedAddresses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    campaigns(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean, boolean] & {
        budget: BigNumber;
        totalClaimed: BigNumber;
        isActive: boolean;
        exists: boolean;
      }
    >;

    cancelClaim(
      ref: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimDateClaim(
      refs: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimDirect(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claims(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, number, string] & {
        recipient: string;
        amount: BigNumber;
        status: number;
        campaignId: string;
      }
    >;

    endCampaign(
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    fundCampaign(
      campaignId: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getCampaignDetails(
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean] & {
        budget: BigNumber;
        totalClaimed: BigNumber;
        isActive: boolean;
      }
    >;

    getClaim(
      ref: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, number] & {
        recipient: string;
        amount: BigNumber;
        status: number;
      }
    >;

    getTreasuryBalance(overrides?: CallOverrides): Promise<[BigNumber]>;

    gsToken(overrides?: CallOverrides): Promise<[string]>;

    initiateClaim(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      ref: PromiseOrValue<BytesLike>,
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isParticipant(
      campaignId: PromiseOrValue<BytesLike>,
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    joinCampaign(
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    manager(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    participants(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    removeAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setManager(
      _manager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setWhitelistEnabled(
      enabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unblacklistAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unwhitelistAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    whitelist(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    whitelistAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    whitelistEnabled(overrides?: CallOverrides): Promise<[boolean]>;

    whitelistedAddresses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  addAdmin(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  adminList(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  adminTopup(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  adminWithdraw(
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  admins(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  batchBlacklist(
    accounts: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  batchSend(
    recipients: PromiseOrValue<string>[],
    amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  batchWhitelist(
    accounts: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  blacklist(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  blacklistAddress(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  blacklistedAddresses(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  campaigns(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, boolean, boolean] & {
      budget: BigNumber;
      totalClaimed: BigNumber;
      isActive: boolean;
      exists: boolean;
    }
  >;

  cancelClaim(
    ref: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimDateClaim(
    refs: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimDirect(
    recipient: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    campaignId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claims(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, number, string] & {
      recipient: string;
      amount: BigNumber;
      status: number;
      campaignId: string;
    }
  >;

  endCampaign(
    campaignId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  fundCampaign(
    campaignId: PromiseOrValue<BytesLike>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getCampaignDetails(
    campaignId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, boolean] & {
      budget: BigNumber;
      totalClaimed: BigNumber;
      isActive: boolean;
    }
  >;

  getClaim(
    ref: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, number] & {
      recipient: string;
      amount: BigNumber;
      status: number;
    }
  >;

  getTreasuryBalance(overrides?: CallOverrides): Promise<BigNumber>;

  gsToken(overrides?: CallOverrides): Promise<string>;

  initiateClaim(
    recipient: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    ref: PromiseOrValue<BytesLike>,
    campaignId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isParticipant(
    campaignId: PromiseOrValue<BytesLike>,
    user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  joinCampaign(
    campaignId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  manager(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  participants(
    arg0: PromiseOrValue<BytesLike>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  removeAdmin(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setManager(
    _manager: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setWhitelistEnabled(
    enabled: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unblacklistAddress(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unwhitelistAddress(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  whitelist(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  whitelistAddress(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  whitelistEnabled(overrides?: CallOverrides): Promise<boolean>;

  whitelistedAddresses(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    addAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    adminList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    adminTopup(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    adminWithdraw(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    admins(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    batchBlacklist(
      accounts: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    batchSend(
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    batchWhitelist(
      accounts: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    blacklist(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    blacklistAddress(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    blacklistedAddresses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    campaigns(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean, boolean] & {
        budget: BigNumber;
        totalClaimed: BigNumber;
        isActive: boolean;
        exists: boolean;
      }
    >;

    cancelClaim(
      ref: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    claimDateClaim(
      refs: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    claimDirect(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    claims(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, number, string] & {
        recipient: string;
        amount: BigNumber;
        status: number;
        campaignId: string;
      }
    >;

    endCampaign(
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    fundCampaign(
      campaignId: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getCampaignDetails(
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean] & {
        budget: BigNumber;
        totalClaimed: BigNumber;
        isActive: boolean;
      }
    >;

    getClaim(
      ref: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, number] & {
        recipient: string;
        amount: BigNumber;
        status: number;
      }
    >;

    getTreasuryBalance(overrides?: CallOverrides): Promise<BigNumber>;

    gsToken(overrides?: CallOverrides): Promise<string>;

    initiateClaim(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      ref: PromiseOrValue<BytesLike>,
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    isParticipant(
      campaignId: PromiseOrValue<BytesLike>,
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    joinCampaign(
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    manager(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    participants(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    removeAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setManager(
      _manager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setWhitelistEnabled(
      enabled: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unblacklistAddress(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unwhitelistAddress(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelist(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    whitelistAddress(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistEnabled(overrides?: CallOverrides): Promise<boolean>;

    whitelistedAddresses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "AddressBlacklisted(address,uint256)"(
      account?: PromiseOrValue<string> | null,
      timestamp?: null
    ): AddressBlacklistedEventFilter;
    AddressBlacklisted(
      account?: PromiseOrValue<string> | null,
      timestamp?: null
    ): AddressBlacklistedEventFilter;

    "AddressUnblacklisted(address,uint256)"(
      account?: PromiseOrValue<string> | null,
      timestamp?: null
    ): AddressUnblacklistedEventFilter;
    AddressUnblacklisted(
      account?: PromiseOrValue<string> | null,
      timestamp?: null
    ): AddressUnblacklistedEventFilter;

    "AddressUnwhitelisted(address,uint256)"(
      account?: PromiseOrValue<string> | null,
      timestamp?: null
    ): AddressUnwhitelistedEventFilter;
    AddressUnwhitelisted(
      account?: PromiseOrValue<string> | null,
      timestamp?: null
    ): AddressUnwhitelistedEventFilter;

    "AddressWhitelisted(address,uint256)"(
      account?: PromiseOrValue<string> | null,
      timestamp?: null
    ): AddressWhitelistedEventFilter;
    AddressWhitelisted(
      account?: PromiseOrValue<string> | null,
      timestamp?: null
    ): AddressWhitelistedEventFilter;

    "AdminAdded(address,uint256)"(
      admin?: PromiseOrValue<string> | null,
      timestamp?: null
    ): AdminAddedEventFilter;
    AdminAdded(
      admin?: PromiseOrValue<string> | null,
      timestamp?: null
    ): AdminAddedEventFilter;

    "AdminRemoved(address,uint256)"(
      admin?: PromiseOrValue<string> | null,
      timestamp?: null
    ): AdminRemovedEventFilter;
    AdminRemoved(
      admin?: PromiseOrValue<string> | null,
      timestamp?: null
    ): AdminRemovedEventFilter;

    "AdminTopup(address,uint256,uint256)"(
      token?: PromiseOrValue<string> | null,
      amount?: null,
      timestamp?: null
    ): AdminTopupEventFilter;
    AdminTopup(
      token?: PromiseOrValue<string> | null,
      amount?: null,
      timestamp?: null
    ): AdminTopupEventFilter;

    "AdminWithdraw(address,address,uint256,uint256)"(
      token?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      amount?: null,
      timestamp?: null
    ): AdminWithdrawEventFilter;
    AdminWithdraw(
      token?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      amount?: null,
      timestamp?: null
    ): AdminWithdrawEventFilter;

    "BatchSend(address,uint256,uint256,uint256)"(
      token?: PromiseOrValue<string> | null,
      totalAmount?: null,
      recipientCount?: null,
      timestamp?: null
    ): BatchSendEventFilter;
    BatchSend(
      token?: PromiseOrValue<string> | null,
      totalAmount?: null,
      recipientCount?: null,
      timestamp?: null
    ): BatchSendEventFilter;

    "CampaignEnded(bytes32,uint256)"(
      campaignId?: PromiseOrValue<BytesLike> | null,
      timestamp?: null
    ): CampaignEndedEventFilter;
    CampaignEnded(
      campaignId?: PromiseOrValue<BytesLike> | null,
      timestamp?: null
    ): CampaignEndedEventFilter;

    "CampaignFunded(bytes32,uint256,uint256)"(
      campaignId?: PromiseOrValue<BytesLike> | null,
      amount?: null,
      timestamp?: null
    ): CampaignFundedEventFilter;
    CampaignFunded(
      campaignId?: PromiseOrValue<BytesLike> | null,
      amount?: null,
      timestamp?: null
    ): CampaignFundedEventFilter;

    "CampaignJoined(bytes32,address,uint256)"(
      campaignId?: PromiseOrValue<BytesLike> | null,
      participant?: PromiseOrValue<string> | null,
      timestamp?: null
    ): CampaignJoinedEventFilter;
    CampaignJoined(
      campaignId?: PromiseOrValue<BytesLike> | null,
      participant?: PromiseOrValue<string> | null,
      timestamp?: null
    ): CampaignJoinedEventFilter;

    "ClaimCancelled(bytes32,uint256)"(
      ref?: PromiseOrValue<BytesLike> | null,
      timestamp?: null
    ): ClaimCancelledEventFilter;
    ClaimCancelled(
      ref?: PromiseOrValue<BytesLike> | null,
      timestamp?: null
    ): ClaimCancelledEventFilter;

    "ClaimDirect(address,uint256,uint256)"(
      recipient?: PromiseOrValue<string> | null,
      amount?: null,
      timestamp?: null
    ): ClaimDirectEventFilter;
    ClaimDirect(
      recipient?: PromiseOrValue<string> | null,
      amount?: null,
      timestamp?: null
    ): ClaimDirectEventFilter;

    "ClaimDistributed(bytes32,address,uint256,uint256)"(
      ref?: PromiseOrValue<BytesLike> | null,
      recipient?: PromiseOrValue<string> | null,
      amount?: null,
      timestamp?: null
    ): ClaimDistributedEventFilter;
    ClaimDistributed(
      ref?: PromiseOrValue<BytesLike> | null,
      recipient?: PromiseOrValue<string> | null,
      amount?: null,
      timestamp?: null
    ): ClaimDistributedEventFilter;

    "ClaimInitiated(bytes32,address,uint256,uint256)"(
      ref?: PromiseOrValue<BytesLike> | null,
      recipient?: PromiseOrValue<string> | null,
      amount?: null,
      timestamp?: null
    ): ClaimInitiatedEventFilter;
    ClaimInitiated(
      ref?: PromiseOrValue<BytesLike> | null,
      recipient?: PromiseOrValue<string> | null,
      amount?: null,
      timestamp?: null
    ): ClaimInitiatedEventFilter;

    "ManagerUpdated(address,uint256)"(
      manager?: PromiseOrValue<string> | null,
      timestamp?: null
    ): ManagerUpdatedEventFilter;
    ManagerUpdated(
      manager?: PromiseOrValue<string> | null,
      timestamp?: null
    ): ManagerUpdatedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "WhitelistToggled(bool,uint256)"(
      enabled?: null,
      timestamp?: null
    ): WhitelistToggledEventFilter;
    WhitelistToggled(
      enabled?: null,
      timestamp?: null
    ): WhitelistToggledEventFilter;
  };

  estimateGas: {
    addAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    adminList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    adminTopup(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    adminWithdraw(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    admins(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    batchBlacklist(
      accounts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    batchSend(
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    batchWhitelist(
      accounts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    blacklist(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    blacklistAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    blacklistedAddresses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    campaigns(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelClaim(
      ref: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimDateClaim(
      refs: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimDirect(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claims(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    endCampaign(
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    fundCampaign(
      campaignId: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getCampaignDetails(
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getClaim(
      ref: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTreasuryBalance(overrides?: CallOverrides): Promise<BigNumber>;

    gsToken(overrides?: CallOverrides): Promise<BigNumber>;

    initiateClaim(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      ref: PromiseOrValue<BytesLike>,
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isParticipant(
      campaignId: PromiseOrValue<BytesLike>,
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    joinCampaign(
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    manager(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    participants(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setManager(
      _manager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setWhitelistEnabled(
      enabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unblacklistAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unwhitelistAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    whitelist(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    whitelistAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    whitelistEnabled(overrides?: CallOverrides): Promise<BigNumber>;

    whitelistedAddresses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    adminList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    adminTopup(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    adminWithdraw(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    admins(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    batchBlacklist(
      accounts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    batchSend(
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    batchWhitelist(
      accounts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    blacklist(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    blacklistAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    blacklistedAddresses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    campaigns(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelClaim(
      ref: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimDateClaim(
      refs: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimDirect(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claims(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    endCampaign(
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    fundCampaign(
      campaignId: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getCampaignDetails(
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getClaim(
      ref: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTreasuryBalance(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gsToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initiateClaim(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      ref: PromiseOrValue<BytesLike>,
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isParticipant(
      campaignId: PromiseOrValue<BytesLike>,
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    joinCampaign(
      campaignId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    manager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    participants(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setManager(
      _manager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setWhitelistEnabled(
      enabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unblacklistAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unwhitelistAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    whitelist(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    whitelistAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    whitelistEnabled(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    whitelistedAddresses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
