/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace SovAdsManager {
  export type CampaignVaultStruct = {
    token: PromiseOrValue<string>;
    totalFunded: PromiseOrValue<BigNumberish>;
    locked: PromiseOrValue<BigNumberish>;
    claimed: PromiseOrValue<BigNumberish>;
  };

  export type CampaignVaultStructOutput = [
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    token: string;
    totalFunded: BigNumber;
    locked: BigNumber;
    claimed: BigNumber;
  };
}

export interface SovAdsManagerInterface extends utils.Interface {
  functions: {
    "addSite(string)": FunctionFragment;
    "addSupportedToken(address)": FunctionFragment;
    "admins(address)": FunctionFragment;
    "campaignCount()": FunctionFragment;
    "campaigns(uint256)": FunctionFragment;
    "claimCount()": FunctionFragment;
    "claims(uint256)": FunctionFragment;
    "clickRate()": FunctionFragment;
    "createCampaign(address,uint256,uint256,string)": FunctionFragment;
    "createClaim(uint256,uint256)": FunctionFragment;
    "disburseFunds(uint256,address,uint256)": FunctionFragment;
    "feePercent()": FunctionFragment;
    "feeRecipient()": FunctionFragment;
    "getBalanceInfo(uint256,address)": FunctionFragment;
    "getCampaignVault(uint256)": FunctionFragment;
    "impressionRate()": FunctionFragment;
    "isPublisher(address)": FunctionFragment;
    "isViewer(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "processClaim(uint256,bool)": FunctionFragment;
    "publishers(address)": FunctionFragment;
    "recordInteraction(uint256,address,uint256,string)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setAdmin(address,bool)": FunctionFragment;
    "setFeeConfig(address,uint256)": FunctionFragment;
    "setRates(uint256,uint256)": FunctionFragment;
    "subscribePublisher(string[])": FunctionFragment;
    "supportedTokens(address)": FunctionFragment;
    "topUpCampaign(uint256,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unpause()": FunctionFragment;
    "valuations(uint256,address)": FunctionFragment;
    "viewers(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addSite"
      | "addSupportedToken"
      | "admins"
      | "campaignCount"
      | "campaigns"
      | "claimCount"
      | "claims"
      | "clickRate"
      | "createCampaign"
      | "createClaim"
      | "disburseFunds"
      | "feePercent"
      | "feeRecipient"
      | "getBalanceInfo"
      | "getCampaignVault"
      | "impressionRate"
      | "isPublisher"
      | "isViewer"
      | "owner"
      | "pause"
      | "paused"
      | "processClaim"
      | "publishers"
      | "recordInteraction"
      | "renounceOwnership"
      | "setAdmin"
      | "setFeeConfig"
      | "setRates"
      | "subscribePublisher"
      | "supportedTokens"
      | "topUpCampaign"
      | "transferOwnership"
      | "unpause"
      | "valuations"
      | "viewers"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addSite",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addSupportedToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "admins",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claims",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "clickRate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createClaim",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "disburseFunds",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "feePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalanceInfo",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignVault",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "impressionRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isPublisher",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isViewer",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processClaim",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "publishers",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "recordInteraction",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAdmin",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeConfig",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRates",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribePublisher",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "topUpCampaign",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "valuations",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "viewers",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "addSite", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "campaignCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claims", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "clickRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disburseFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feePercent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBalanceInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "impressionRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPublisher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isViewer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "publishers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordInteraction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscribePublisher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "topUpCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "valuations", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "viewers", data: BytesLike): Result;

  events: {
    "CampaignCreated(uint256,address,address,uint256)": EventFragment;
    "CampaignFunded(uint256,uint256)": EventFragment;
    "ClaimCreated(uint256,uint256,address,uint256)": EventFragment;
    "ClaimProcessed(uint256,address,uint256,bool)": EventFragment;
    "InteractionRecorded(uint256,address,uint256,string)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "PublisherSubscribed(address,string[])": EventFragment;
    "RateUpdated(string,uint256)": EventFragment;
    "SiteAdded(address,string)": EventFragment;
    "Unpaused(address)": EventFragment;
    "UserBanned(address)": EventFragment;
    "UserUnbanned(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CampaignCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CampaignFunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimProcessed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InteractionRecorded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PublisherSubscribed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RateUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SiteAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UserBanned"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UserUnbanned"): EventFragment;
}

export interface CampaignCreatedEventObject {
  id: BigNumber;
  creator: string;
  token: string;
  amount: BigNumber;
}
export type CampaignCreatedEvent = TypedEvent<
  [BigNumber, string, string, BigNumber],
  CampaignCreatedEventObject
>;

export type CampaignCreatedEventFilter = TypedEventFilter<CampaignCreatedEvent>;

export interface CampaignFundedEventObject {
  id: BigNumber;
  amount: BigNumber;
}
export type CampaignFundedEvent = TypedEvent<
  [BigNumber, BigNumber],
  CampaignFundedEventObject
>;

export type CampaignFundedEventFilter = TypedEventFilter<CampaignFundedEvent>;

export interface ClaimCreatedEventObject {
  claimId: BigNumber;
  campaignId: BigNumber;
  claimant: string;
  amount: BigNumber;
}
export type ClaimCreatedEvent = TypedEvent<
  [BigNumber, BigNumber, string, BigNumber],
  ClaimCreatedEventObject
>;

export type ClaimCreatedEventFilter = TypedEventFilter<ClaimCreatedEvent>;

export interface ClaimProcessedEventObject {
  claimId: BigNumber;
  claimant: string;
  amount: BigNumber;
  approved: boolean;
}
export type ClaimProcessedEvent = TypedEvent<
  [BigNumber, string, BigNumber, boolean],
  ClaimProcessedEventObject
>;

export type ClaimProcessedEventFilter = TypedEventFilter<ClaimProcessedEvent>;

export interface InteractionRecordedEventObject {
  campaignId: BigNumber;
  user: string;
  value: BigNumber;
  interactionType: string;
}
export type InteractionRecordedEvent = TypedEvent<
  [BigNumber, string, BigNumber, string],
  InteractionRecordedEventObject
>;

export type InteractionRecordedEventFilter =
  TypedEventFilter<InteractionRecordedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface PublisherSubscribedEventObject {
  publisher: string;
  sites: string[];
}
export type PublisherSubscribedEvent = TypedEvent<
  [string, string[]],
  PublisherSubscribedEventObject
>;

export type PublisherSubscribedEventFilter =
  TypedEventFilter<PublisherSubscribedEvent>;

export interface RateUpdatedEventObject {
  rateType: string;
  newValue: BigNumber;
}
export type RateUpdatedEvent = TypedEvent<
  [string, BigNumber],
  RateUpdatedEventObject
>;

export type RateUpdatedEventFilter = TypedEventFilter<RateUpdatedEvent>;

export interface SiteAddedEventObject {
  publisher: string;
  site: string;
}
export type SiteAddedEvent = TypedEvent<[string, string], SiteAddedEventObject>;

export type SiteAddedEventFilter = TypedEventFilter<SiteAddedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface UserBannedEventObject {
  user: string;
}
export type UserBannedEvent = TypedEvent<[string], UserBannedEventObject>;

export type UserBannedEventFilter = TypedEventFilter<UserBannedEvent>;

export interface UserUnbannedEventObject {
  user: string;
}
export type UserUnbannedEvent = TypedEvent<[string], UserUnbannedEventObject>;

export type UserUnbannedEventFilter = TypedEventFilter<UserUnbannedEvent>;

export interface SovAdsManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SovAdsManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addSite(
      _site: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addSupportedToken(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    admins(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    campaignCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    campaigns(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        boolean,
        boolean,
        SovAdsManager.CampaignVaultStructOutput
      ] & {
        id: BigNumber;
        creator: string;
        startTime: BigNumber;
        endTime: BigNumber;
        metadata: string;
        active: boolean;
        paused: boolean;
        vault: SovAdsManager.CampaignVaultStructOutput;
      }
    >;

    claimCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    claims(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        boolean,
        boolean,
        BigNumber,
        BigNumber
      ] & {
        id: BigNumber;
        campaignId: BigNumber;
        claimant: string;
        amount: BigNumber;
        processed: boolean;
        rejected: boolean;
        createdAt: BigNumber;
        processedAt: BigNumber;
      }
    >;

    clickRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    createCampaign(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      _metadata: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createClaim(
      _campaignId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    disburseFunds(
      _campaignId: PromiseOrValue<BigNumberish>,
      _recipient: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    feePercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    feeRecipient(overrides?: CallOverrides): Promise<[string]>;

    getBalanceInfo(
      _campaignId: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        accrued: BigNumber;
        claimed: BigNumber;
        pending: BigNumber;
      }
    >;

    getCampaignVault(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[SovAdsManager.CampaignVaultStructOutput]>;

    impressionRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    isPublisher(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isViewer(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    processClaim(
      _claimId: PromiseOrValue<BigNumberish>,
      _approve: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    publishers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, boolean, BigNumber] & {
        wallet: string;
        banned: boolean;
        subscriptionDate: BigNumber;
      }
    >;

    recordInteraction(
      _campaignId: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      _count: PromiseOrValue<BigNumberish>,
      _type: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAdmin(
      _admin: PromiseOrValue<string>,
      _status: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFeeConfig(
      _recipient: PromiseOrValue<string>,
      _bps: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRates(
      _impressionRate: PromiseOrValue<BigNumberish>,
      _clickRate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    subscribePublisher(
      _sites: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    topUpCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    valuations(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        impressions: BigNumber;
        clicks: BigNumber;
        valueAccrued: BigNumber;
        valueClaimed: BigNumber;
      }
    >;

    viewers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, boolean, BigNumber] & {
        wallet: string;
        active: boolean;
        lastInteraction: BigNumber;
      }
    >;
  };

  addSite(
    _site: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addSupportedToken(
    _token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  admins(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  campaignCount(overrides?: CallOverrides): Promise<BigNumber>;

  campaigns(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      string,
      boolean,
      boolean,
      SovAdsManager.CampaignVaultStructOutput
    ] & {
      id: BigNumber;
      creator: string;
      startTime: BigNumber;
      endTime: BigNumber;
      metadata: string;
      active: boolean;
      paused: boolean;
      vault: SovAdsManager.CampaignVaultStructOutput;
    }
  >;

  claimCount(overrides?: CallOverrides): Promise<BigNumber>;

  claims(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      boolean,
      boolean,
      BigNumber,
      BigNumber
    ] & {
      id: BigNumber;
      campaignId: BigNumber;
      claimant: string;
      amount: BigNumber;
      processed: boolean;
      rejected: boolean;
      createdAt: BigNumber;
      processedAt: BigNumber;
    }
  >;

  clickRate(overrides?: CallOverrides): Promise<BigNumber>;

  createCampaign(
    _token: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    _duration: PromiseOrValue<BigNumberish>,
    _metadata: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createClaim(
    _campaignId: PromiseOrValue<BigNumberish>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  disburseFunds(
    _campaignId: PromiseOrValue<BigNumberish>,
    _recipient: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  feePercent(overrides?: CallOverrides): Promise<BigNumber>;

  feeRecipient(overrides?: CallOverrides): Promise<string>;

  getBalanceInfo(
    _campaignId: PromiseOrValue<BigNumberish>,
    _user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      accrued: BigNumber;
      claimed: BigNumber;
      pending: BigNumber;
    }
  >;

  getCampaignVault(
    _campaignId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<SovAdsManager.CampaignVaultStructOutput>;

  impressionRate(overrides?: CallOverrides): Promise<BigNumber>;

  isPublisher(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isViewer(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  processClaim(
    _claimId: PromiseOrValue<BigNumberish>,
    _approve: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  publishers(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [string, boolean, BigNumber] & {
      wallet: string;
      banned: boolean;
      subscriptionDate: BigNumber;
    }
  >;

  recordInteraction(
    _campaignId: PromiseOrValue<BigNumberish>,
    _user: PromiseOrValue<string>,
    _count: PromiseOrValue<BigNumberish>,
    _type: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAdmin(
    _admin: PromiseOrValue<string>,
    _status: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFeeConfig(
    _recipient: PromiseOrValue<string>,
    _bps: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRates(
    _impressionRate: PromiseOrValue<BigNumberish>,
    _clickRate: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  subscribePublisher(
    _sites: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportedTokens(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  topUpCampaign(
    _campaignId: PromiseOrValue<BigNumberish>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  valuations(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      impressions: BigNumber;
      clicks: BigNumber;
      valueAccrued: BigNumber;
      valueClaimed: BigNumber;
    }
  >;

  viewers(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [string, boolean, BigNumber] & {
      wallet: string;
      active: boolean;
      lastInteraction: BigNumber;
    }
  >;

  callStatic: {
    addSite(
      _site: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addSupportedToken(
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    admins(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    campaignCount(overrides?: CallOverrides): Promise<BigNumber>;

    campaigns(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        boolean,
        boolean,
        SovAdsManager.CampaignVaultStructOutput
      ] & {
        id: BigNumber;
        creator: string;
        startTime: BigNumber;
        endTime: BigNumber;
        metadata: string;
        active: boolean;
        paused: boolean;
        vault: SovAdsManager.CampaignVaultStructOutput;
      }
    >;

    claimCount(overrides?: CallOverrides): Promise<BigNumber>;

    claims(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        boolean,
        boolean,
        BigNumber,
        BigNumber
      ] & {
        id: BigNumber;
        campaignId: BigNumber;
        claimant: string;
        amount: BigNumber;
        processed: boolean;
        rejected: boolean;
        createdAt: BigNumber;
        processedAt: BigNumber;
      }
    >;

    clickRate(overrides?: CallOverrides): Promise<BigNumber>;

    createCampaign(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      _metadata: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    createClaim(
      _campaignId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    disburseFunds(
      _campaignId: PromiseOrValue<BigNumberish>,
      _recipient: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    feePercent(overrides?: CallOverrides): Promise<BigNumber>;

    feeRecipient(overrides?: CallOverrides): Promise<string>;

    getBalanceInfo(
      _campaignId: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        accrued: BigNumber;
        claimed: BigNumber;
        pending: BigNumber;
      }
    >;

    getCampaignVault(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<SovAdsManager.CampaignVaultStructOutput>;

    impressionRate(overrides?: CallOverrides): Promise<BigNumber>;

    isPublisher(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isViewer(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    processClaim(
      _claimId: PromiseOrValue<BigNumberish>,
      _approve: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    publishers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, boolean, BigNumber] & {
        wallet: string;
        banned: boolean;
        subscriptionDate: BigNumber;
      }
    >;

    recordInteraction(
      _campaignId: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      _count: PromiseOrValue<BigNumberish>,
      _type: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setAdmin(
      _admin: PromiseOrValue<string>,
      _status: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFeeConfig(
      _recipient: PromiseOrValue<string>,
      _bps: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRates(
      _impressionRate: PromiseOrValue<BigNumberish>,
      _clickRate: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    subscribePublisher(
      _sites: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    supportedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    topUpCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    valuations(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        impressions: BigNumber;
        clicks: BigNumber;
        valueAccrued: BigNumber;
        valueClaimed: BigNumber;
      }
    >;

    viewers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, boolean, BigNumber] & {
        wallet: string;
        active: boolean;
        lastInteraction: BigNumber;
      }
    >;
  };

  filters: {
    "CampaignCreated(uint256,address,address,uint256)"(
      id?: PromiseOrValue<BigNumberish> | null,
      creator?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      amount?: null
    ): CampaignCreatedEventFilter;
    CampaignCreated(
      id?: PromiseOrValue<BigNumberish> | null,
      creator?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      amount?: null
    ): CampaignCreatedEventFilter;

    "CampaignFunded(uint256,uint256)"(
      id?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): CampaignFundedEventFilter;
    CampaignFunded(
      id?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): CampaignFundedEventFilter;

    "ClaimCreated(uint256,uint256,address,uint256)"(
      claimId?: PromiseOrValue<BigNumberish> | null,
      campaignId?: PromiseOrValue<BigNumberish> | null,
      claimant?: PromiseOrValue<string> | null,
      amount?: null
    ): ClaimCreatedEventFilter;
    ClaimCreated(
      claimId?: PromiseOrValue<BigNumberish> | null,
      campaignId?: PromiseOrValue<BigNumberish> | null,
      claimant?: PromiseOrValue<string> | null,
      amount?: null
    ): ClaimCreatedEventFilter;

    "ClaimProcessed(uint256,address,uint256,bool)"(
      claimId?: PromiseOrValue<BigNumberish> | null,
      claimant?: PromiseOrValue<string> | null,
      amount?: null,
      approved?: null
    ): ClaimProcessedEventFilter;
    ClaimProcessed(
      claimId?: PromiseOrValue<BigNumberish> | null,
      claimant?: PromiseOrValue<string> | null,
      amount?: null,
      approved?: null
    ): ClaimProcessedEventFilter;

    "InteractionRecorded(uint256,address,uint256,string)"(
      campaignId?: PromiseOrValue<BigNumberish> | null,
      user?: PromiseOrValue<string> | null,
      value?: null,
      interactionType?: null
    ): InteractionRecordedEventFilter;
    InteractionRecorded(
      campaignId?: PromiseOrValue<BigNumberish> | null,
      user?: PromiseOrValue<string> | null,
      value?: null,
      interactionType?: null
    ): InteractionRecordedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "PublisherSubscribed(address,string[])"(
      publisher?: PromiseOrValue<string> | null,
      sites?: null
    ): PublisherSubscribedEventFilter;
    PublisherSubscribed(
      publisher?: PromiseOrValue<string> | null,
      sites?: null
    ): PublisherSubscribedEventFilter;

    "RateUpdated(string,uint256)"(
      rateType?: null,
      newValue?: null
    ): RateUpdatedEventFilter;
    RateUpdated(rateType?: null, newValue?: null): RateUpdatedEventFilter;

    "SiteAdded(address,string)"(
      publisher?: PromiseOrValue<string> | null,
      site?: null
    ): SiteAddedEventFilter;
    SiteAdded(
      publisher?: PromiseOrValue<string> | null,
      site?: null
    ): SiteAddedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;

    "UserBanned(address)"(
      user?: PromiseOrValue<string> | null
    ): UserBannedEventFilter;
    UserBanned(user?: PromiseOrValue<string> | null): UserBannedEventFilter;

    "UserUnbanned(address)"(
      user?: PromiseOrValue<string> | null
    ): UserUnbannedEventFilter;
    UserUnbanned(user?: PromiseOrValue<string> | null): UserUnbannedEventFilter;
  };

  estimateGas: {
    addSite(
      _site: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addSupportedToken(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    admins(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    campaignCount(overrides?: CallOverrides): Promise<BigNumber>;

    campaigns(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimCount(overrides?: CallOverrides): Promise<BigNumber>;

    claims(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    clickRate(overrides?: CallOverrides): Promise<BigNumber>;

    createCampaign(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      _metadata: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createClaim(
      _campaignId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    disburseFunds(
      _campaignId: PromiseOrValue<BigNumberish>,
      _recipient: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    feePercent(overrides?: CallOverrides): Promise<BigNumber>;

    feeRecipient(overrides?: CallOverrides): Promise<BigNumber>;

    getBalanceInfo(
      _campaignId: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCampaignVault(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    impressionRate(overrides?: CallOverrides): Promise<BigNumber>;

    isPublisher(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isViewer(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    processClaim(
      _claimId: PromiseOrValue<BigNumberish>,
      _approve: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    publishers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recordInteraction(
      _campaignId: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      _count: PromiseOrValue<BigNumberish>,
      _type: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAdmin(
      _admin: PromiseOrValue<string>,
      _status: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFeeConfig(
      _recipient: PromiseOrValue<string>,
      _bps: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRates(
      _impressionRate: PromiseOrValue<BigNumberish>,
      _clickRate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    subscribePublisher(
      _sites: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    topUpCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    valuations(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    viewers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addSite(
      _site: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addSupportedToken(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    admins(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    campaignCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    campaigns(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claims(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    clickRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createCampaign(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      _metadata: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createClaim(
      _campaignId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    disburseFunds(
      _campaignId: PromiseOrValue<BigNumberish>,
      _recipient: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    feePercent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeRecipient(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBalanceInfo(
      _campaignId: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCampaignVault(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    impressionRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isPublisher(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isViewer(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    processClaim(
      _claimId: PromiseOrValue<BigNumberish>,
      _approve: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    publishers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recordInteraction(
      _campaignId: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      _count: PromiseOrValue<BigNumberish>,
      _type: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAdmin(
      _admin: PromiseOrValue<string>,
      _status: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFeeConfig(
      _recipient: PromiseOrValue<string>,
      _bps: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRates(
      _impressionRate: PromiseOrValue<BigNumberish>,
      _clickRate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    subscribePublisher(
      _sites: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    topUpCampaign(
      _campaignId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    valuations(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    viewers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
